### ISSUE TITLE
Glitch website

### ISSUE THREAD

**Issue by richyjat** [theADAMJR/2PG-Dashboard#1]
An unhandled exception occurred: Script file node_modules/jquery/dist/jquery.min.js does not exist.
See "/tmp/ng-Cyd3bs/angular-errors.log" for further details.

**Comment by theADAMJR** [comment]
`npm i --save jquery` on dashboard.
I believe it was deleted as it was messing with the JavaScript DOM.
It should now be readded to package.json.
